#!/bin/bash -e

# Create root CA key
openssl genrsa -des3 -out rootCA.key 4096

# Create root CA certificate
openssl req -x509 -new -nodes -key certs/rootCA.key -sha256 -days 1024  -out certs/rootCA.crt -config rootCA.conf

# Create certificate signing request (csr) & server key
openssl req -new -nodes -out certs/localhost.csr -newkey rsa:2048 -keyout certs/localhost.key -config localhost.conf

# Create certificate using csr and and root CA
openssl x509 -req -in certs/localhost.csr -CA certs/rootCA.crt -CAkey certs/rootCA.key -CAcreateserial -out certs/localhost.crt -days 1024 -sha256 -extfile v3.ext
